config/urls.py
from django.contrib import admin
from django.urls import path, include
from sales import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls')), # 원래는 'sales/' 였음. map 땜시 잠시 뺌
    path('common/', include('common.urls')),
    path('', views.map, name='map'), # / 페이지에 해당하는 urlpatterns
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.map, name='map'),
    path('<int:product_id>/', views.detail, name='detail'),
    path('product/create/', views.product_create, name='product_create'),
    path('product/modify/<int:product_id>/', views.product_modify, name='product_modify'),
    path('product/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product/product_list/', views.index, name='index'),
    path('salesinfo/', views.salesinfo_index, name='salesinfo_index'),
    path('salesinfo/<int:salesinfo_id>/', views.salesinfo_detail, name='salesinfo_detail'),
    path('salesinfo/crete/', views.salesinfo_create, name='salesinfo_create'),
    path('salesinfo/modify/<int:salesinfo_id>/', views.salesinfo_modify, name='salesinfo_modify'),
    path('salesinfo/delete/<int:salesinfo_id>/', views.salesinfo_delete, name='salesinfo_delete'),
]

sales/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import json
import os

class Product(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # User는 django.contrib.auth.models가 제공하는 모델
    modify_date = models.DateTimeField(null=True, blank=True)
    pcode = models.CharField(max_length=10)
    pname = models.TextField()
    unitprice = models.IntegerField(default=0)
    discountrate = models.DecimalField(max_digits=11, decimal_places=2,default=0)
    mainfunc = models.CharField(max_length=100, default="")
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    detailfunc = models.CharField(max_length=200, default="")

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return f"{self.pcode} {self.pname} {self.unitprice} {self.discountrate} {self.mainfunc}"


class SalesInfo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)
    scode = models.CharField(max_length=10, null=False, blank=False)
    sale_date = models.DateTimeField(null=False, blank=False)
    qty = models.IntegerField(default=1)
    amt = models.IntegerField(default=0)
    main_inst = models.CharField(max_length=4, default="")
    detail_inst = models.TextField(default="")

class Sales_History(models.Model):
    udate = models.DateTimeField(null=True, blank=True)
    scode = models.CharField(max_length=10)
    sale_date = models.DateTimeField(null=False, blank=False)
    qty = models.IntegerField(default=1)
    amt = models.IntegerField(default=0)
    main_inst = models.CharField(max_length=4, default="")
    detail_inst = models.TextField(default="")
    uexplain = models.CharField(max_length=20, null=False)
    def publish(self):
        self.published_date = timezone.now()
        self.save()

sales/forms.py
from django import forms
from sales.models import Product, SalesInfo

class ProductForm(forms.ModelForm): # ModelForm 은 장고 모델 폼
    class Meta: # 장고 모델 폼은 반드시 내부에 Meta 클래스 가져야 함
        model = Product
        fields = ['pcode', 'pname', 'unitprice', 'discountrate', 'mainfunc', 'detailfunc', 'imgfile']
        labels = {
            'pcode': '제품 코드 ',
            'pname': '제 품 명 ',
            'unitprice': '단    가 ',
            'discountrate': '할 인 율 ',
            'mainfunc': '주요 기능',
            'detailfunc': '상세 기능',
            'imgfile': '이 미 지'
        }

class SalesInfoForm(forms.ModelForm):
    class Meta:
        model = SalesInfo
        fields = ['scode', 'sale_date', 'qty', 'amt', 'main_inst', 'detail_inst']
        labels = {
            'scode': '판매 제품 코드',
            'sale_date': '판매 일자',
            'qty': '판매 수량',
            'amt': '판매 금액',
            'main_inst': '구매처 분류',
            'detail_inst': '상세 주소',
        }

sales/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, SalesInfo, Sales_History
from .forms import ProductForm, SalesInfoForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
import re
from django.db.models import Q

# Create your views here.
def map(request):
    """
        map 조회
        """
    return render(request, 'sales/map.html')

@login_required(login_url='common:login')
def index(request):
    """
    product 목록 출력
    """
    try:
        # 입력 인자
        page = request.GET.get('page', '1') # GET 방식 요청 URL에서 페이지 값 가져옴. 페이지 번호 할당됨. 페이지 파라미터가 없는 URL은 기본값 1 지정
        product_list = Product.objects.order_by('pcode')
        # 페이징 처리
        paginator = Paginator(product_list, 10) # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)

        context = {'product_list':page_obj}
    except EmptyPage: # ?page=1000 같이 페이지 크게 입력할 경우, 마지막 페이지로 이동하도록 대비
        page = paginator.num_pages
        page_obj = paginator.page(page)
    return render(request, 'sales/product_list.html', context) # context의 product 데이터 product_list를
                                                              # sales/product_list.html 파일에 적용
@login_required(login_url='common:login')
def salesinfo_index(request):
    """
    sales 목록 출력
    """
    try:
        # 입력 인자
        page = request.GET.get('page', '1')
        search_mode = request.GET.get('search_mode')
        print(search_mode)
        if search_mode :
            if search_mode == '무상a/s불가':
                sales_list = Sales_History.objects.order_by('udate')
            else:
                sales_list = SalesInfo.objects.filter(main_inst=search_mode).order_by('sale_date')
        else:
            sales_list = SalesInfo.objects.order_by('sale_date')
        # 페이징 처리
        paginator = Paginator(sales_list, 10)
        page_obj = paginator.get_page(page)
        context = {'sales_list':page_obj}
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)
    return render(request, 'sales/sales_list.html', context)


@login_required(login_url='common:login')
def detail(request, product_id):
    """
    sales 내용 출력
    """
    product = get_object_or_404(Product, pk=product_id)
    context = {'product':product}
    return render(request, 'sales/product_detail.html', context)

@login_required(login_url='common:login')
def salesinfo_detail(request, salesinfo_id):
    """
    sales 판매 내용 출력
    """
    salesinfo = get_object_or_404(SalesInfo, pk=salesinfo_id)
    context = {'salesinfo': salesinfo}
    return render(request, 'sales/salesinfo_detail.html', context)


@login_required(login_url='common:login') # 자동으로 로그인 화면으로 이동
def product_create(request):
    """
    sales 제품 등록
    """
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES) # 꼭 !!!! files는 따로 request의 FILES로 속성을 지정해줘야 함
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.detailfunc = product.detailfunc.replace("'", "").replace("[", "").replace("]", "")
            product.save()
            return redirect('sales:index')
    else:
        form = ProductForm() # request.method 가 'GET'인 경우
    context = {'form':form}
    return render(request, 'sales/product_form.html', context)

@login_required(login_url='common:login') # 자동으로 로그인 화면으로 이동
def salesinfo_create(request):
    """
    sales 판매 등록
    """
    if request.method == 'POST':
        form = SalesInfoForm(request.POST)
        if form.is_valid():
            salesinfo = form.save(commit=False)
            salesinfo.author = request.user
            salesinfo.save()
            return redirect('sales:salesinfo_index')
    else:
        form = ProductForm() # request.method 가 'GET'인 경우
    context = {'form':form}
    return render(request, 'sales/salesinfo_form.html', context)

@login_required(login_url='common:login')
def product_modify(request, product_id):
    """
    sales 제품 수정
    """
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('sales:detail', product_id=product.id)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product) # instance는 기존 값을 폼에 채움. imgfile도 있어서 request.FILES 추가
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.detailfunc = product.detailfunc.replace("'", "").replace("[","").replace("]","")
            product.modify_date = timezone.now()
            product.save()
            return redirect('sales:detail', product_id=product.id)

    else:
        form = ProductForm(instance=product)
    context = {'form': form}
    return render(request, 'sales/product_form.html', context)

@login_required(login_url='common:login')
def salesinfo_modify(request, salesinfo_id):
    """
    sales 판매 수정
    """
    salesinfo = get_object_or_404(SalesInfo, pk=salesinfo_id)
    if request.user != salesinfo.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('sales:salesinfo_detail', salesinfo_id=salesinfo.id)

    if request.method == "POST":
        form = SalesInfoForm(request.POST, instance=salesinfo) # instance는 기존 값을 폼에 채움. imgfile도 있어서 request.FILES 추가
        if form.is_valid():
            salesinfo = form.save(commit=False)
            salesinfo.author = request.user
            salesinfo.modify_date = timezone.now()
            salesinfo.save()
            return redirect('sales:salesinfo_detail', salesinfo_id=salesinfo.id)

    else:
        form = SalesInfoForm(instance=salesinfo)
    context = {'form': form}
    return render(request, 'sales/salesinfo_form.html', context)

@login_required(login_url='common:login')
def product_delete(request, product_id):
    """
    sales 제품 삭제
    """
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('sales:detail', product_id=product.id)
    product.delete()
    return redirect('sales:index')

@login_required(login_url='common:login')
def salesinfo_delete(request, salesinfo_id):
    """
    sales 판매 삭제
    """
    salesinfo = get_object_or_404(SalesInfo, pk=salesinfo_id)
    if request.user != salesinfo.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('sales:salesinfo_detail', salesinfo_id=salesinfo.id)
    salesinfo.delete()
    return redirect('sales:salesinfo_index')

templates/sales/map.html
{% extends 'base.html' %} <!-- extends는 상속이라는 뜻 -->
{% block content %}
<p style="margin-top:12px; text-size:50px;">위치 검색 서비스</p>
<table>
    <tr>
        <td>주소</td>
        <td><input type="text" name="detailAddress" id="address"></td>
        <td><button type="button" id="searchBtn">검색</button></td>
    </tr>
    <tr>
        <td>상세 주소</td>
        <td><input type="text" name="detailAddress2"></td>
        <td></td>
    </tr>
</table>
<div id="map" style="width:50%;height:400px;"></div>
{% endblock %}
{% block script %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ff50b19354d62e2f0123bcd36f039571&libraries=services"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();

    // 주소로 좌표를 검색합니다
    geocoder.addressSearch('서울특별시 마포구 월드컵북로 502-36', function(result, status) {

        // 정상적으로 검색이 완료됐으면
         if (status === kakao.maps.services.Status.OK) {

            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });

            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0;">우리회사</div>'
            });
            infowindow.open(map, marker);

            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        }
    });
</script>
{% endblock %}

templates/sales/product_detail.html
{% extends 'base.html' %} <!-- extends는 상속이라는 뜻 -->
{% load humanize %}
{% block content %}
<hr align="center" width="30%">
<h2 align="center" style="margin-top:20px;">{{ product.pcode }}</h2>
<!-- 제품 수정 버튼 시작 -->
{% if request.user == product.author %}
<div align="center">
    <a href="{% url 'sales:product_modify' product.id %}" class="btn btn-sm btn-outline-secondary">제품 수정</a>
    <a href="#" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'sales:product_delete' product.id %}">제품 삭제</a>
</div>
{% endif %}
<!-- 제품 수정 버튼 끝 -->
<hr align="center" width="30%"> <!-- 수평선 -->
{% if product.imgfile %}
<div class="container border col-10">
    <div style="width:10%; height:150px; float:left; margin-right:10px;">
        <img src="{{ product.imgfile.url }}" width="700">
    </div>
    <div class="bktable">
        <table class="detailta">
            <tr class="detailtr">
                <th class="detailth">키오스크코드</th>
                <td>{{ product.pcode}}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">키오스크명</th>
                <td>{{ product.pname }}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">단가</th>
                <td>{{ product.unitprice|intcomma }}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">할인율</th>
                <td>{{ product.discountrate }}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">대표 기능</th>
                <td>{{ product.mainfunc }}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">세부 기능</th>
                <td>{{ product.detailfunc }}</td>
            </tr>
            <tr class="detailtr">
                <th class="detailth">작성자</th>
                <td>{{ product.author.username }}</td>
            </tr>
        </table>
    </div>
</div>
{% else %}
<div style="width:100%; height:150px; padding:50px;">
    <table class="table">

        <tr class="thead-light">
            <th>키오스크코드</th>
            <th>키오스크명</th>
            <th>단가</th>
            <th>할인율</th>
            <th>대표 기능</th>
            <th>세부 기능</th>
            <th>작성자</th>
        </tr>
        <tr>
            <td>
                {{ product.pcode}}
            </td>
            <td>
                {{ product.pname }}
            </td>
            <td>
                {{ product.unitprice|intcomma }}
            </td>
            <td>
                {{ product.discountrate }}
            </td>
            <td>
                {{ product.mainfunc }}
            </td>
            <td>
                {{ product.detailfunc }}
            </td>
            <td>
                {{ product.author.username }}
            </td>
        </tr>
    </table>
</div>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/sales/product_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">키오스크 등록</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류 표시 start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 end -->
        <div class="form-group">
            <label for="pcode">제품 코드</label>
            <input type="text" class="form-control" name="pcode" id="pcode" value="{{ form.pcode.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="pname">제 품 명</label>
            <textarea class="form-control" name="pname" id="pname" rows="1" placeholder="정확하게 입력해주세요.">{{ form.pname.value|default_if_none:'' }}</textarea>
        </div>
        <div class="form-group">
            <label for="unitprice">단  가</label>
            <input type="number" class="form-control" name="unitprice" id="unitprice" step="100" value="{{ form.unitprice.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="discountrate">할 인 율</label>
            <input type="number" class="form-control" name="discountrate" id="discountrate" value="{{ form.discountrate.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="mainfunc">주요 기능</label>
            <input type="text" class="form-control" name="mainfunc" id="mainfunc" placeholder="대표적인 기능 기재" value="{{ form.mainfunc.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="imgfile">제품사진 : </label>
            <input type="file" class="form-control" name="imgfile" id="imgfile">
        </div>
        <div class="form-group">
            <p for="detailfunc">상세 기능 :</p>

            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="장애인 키패드">장애인 키패드</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="시각장애인 음성안내">시각장애인 음성안내</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="점자 라벨">점자 라벨</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="이어폰 소켓">이어폰 소켓</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="촉각 모니터">촉각 모니터</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="높이 조절">높이 조절</label></p>
            <p><label><input type="checkbox" class="form-control2" name="detailfunc" value="화면 확대 기능">화면 확대 기능</label></p>
            <p><input type="reset" value="Reset">
        </div>
        <button type="submit" class="btn text-white" style="background-color: #8396BC;">저장하기</button>
    </form>
</div>
{% endblock %}

templates/sales/product_list.html
{% extends 'base.html' %} <!-- extends는 상속이라는 뜻 -->
{% load humanize %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-light">
            <th>번호</th>
            <th>제품코드</th>
            <th>제품명</th>
            <th>단가</th>
            <th>할인율</th>
            <th width="200" height="50">주요기능</th>
            <th width="120" height="50" align="center" valign="top" style="padding-top:15px;">이미지 유무</th>
            <th>작성자</th>
        </tr>
        </thead>
        <tbody>
            {% if product_list %}
                {% for product in product_list %}
            <tr class="text-center">
                <td>{{ forloop.counter }}</td>
                <td>
                    <a>
                        {{ product.pcode}}
                    </a>
                </td>
                <td>
                    <a href="{% url 'sales:detail' product.id %}">
                        {{ product.pname }}
                    </a>
                </td>
                <td>
                    <a>
                        {{ product.unitprice|intcomma }}
                    </a>
                </td>
                <td>
                    <a>
                        {{ product.discountrate }}
                    </a>
                </td>
                <td width="200" height="50">
                    <a>
                        {{ product.mainfunc }}
                    </a>
                </td>
                <td width="120" height="50" align="center" valign="top" style="padding-top:15px;">
                    {% if product.imgfile %}
                    <span class="badge badge-secondary py-1">
                        ◯
                    </span>
                    {% else %}
                    <span class="badge badge-warning py-1">
                        ✕
                    </span>
                    {% endif %}
                </td>
                <td>
                    {{ product.author.username }}
                </td>
            </tr>
                {% endfor %}
            {% else %}
            <tr>
                <p>제품이 없습니다.</p>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if product_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.previous_page_number }}"> <!-- product_list가 page_obj -->
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in product_list.paginator.page_range %}
        {% if page_number >= product_list.number|add:-5 and page_number <= product_list.number|add:5 %}
            {% if page_number == product_list.number %}
            <li class="page-item active" aria-current="page" > <!-- active는 강조 표시 -->
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if product_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
    <a href="{% url 'sales:product_create' %}" class="btn text-white" style="background-color: #8396BC;">
        제품 등록
    </a>
</div>

{% endblock %}

templates/sales/sales_list.html
{% extends 'base.html' %} <!-- extends는 상속이라는 뜻 -->
{% load humanize %}
{% block content %}
<form action="{% url 'sales:salesinfo_index' %}" method="get" id="search_mode">
    <div class="container my-3">
        <select name="search_mode" id="search_mode">
            <option value="">조회 선택</option>
            <option value="공공">공공</option>
            <option value="민간">민간</option>
            <option value="무상a/s불가">무상a/s불가</option>
        </select>
    </div>
</form>
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-light">
            <th>번호</th>
            <th>키오스크코드</th>
            <th>판매일자</th>
            <th>판매수량</th>
            <th width="200" height="50">판매금액</th>
            <th>구매처 분류</th>
            <th>상세 주소</th>
            <th>작성자</th>
        </tr>
        </thead>
        <tbody>
            {% if sales_list %}
                {% for sales in sales_list %}
                <tr class="text-center">
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'sales:salesinfo_detail' sales.id %}">
                            {{ sales.scode }}
                        </a>
                    </td>
                    <td>
                        <a>
                            {{ sales.sale_date|date:'y년 m월 d일 H:i' }}
                        </a>
                    </td>
                    <td>
                        <a>
                            {{ sales.qty|intcomma }}
                        </a>
                    </td>
                    <td width="200" height="50">
                        <a>
                            {{ sales.amt|intcomma }}
                        </a>
                    </td>
                    <td>
                        {{ sales.main_inst }}
                    </td>
                    <td class="text-truncate" style="max-width: 150px;">
                        {{ sales.detail_inst }}
                    </td>
                    <td>
                        {{ sales.author.username }}
                    </td>
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <p>제품이 없습니다.</p>
            </tr>
            {% endif %}
        </tbody>
    </table>
        <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if sales_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ sales_list.previous_page_number }}"> <!-- sales_list가 page_obj -->
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in sales_list.paginator.page_range %}
        {% if page_number >= sales_list.number|add:-5 and page_number <= sales_list.number|add:5 %}
            {% if page_number == sales_list.number %}
            <li class="page-item active" aria-current="page" > <!-- active는 강조 표시 -->
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if sales_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ sales_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->
    <a href="{% url 'sales:salesinfo_create' %}" class="btn text-white" style="background-color: #8396BC;">
        판매 등록
    </a>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $("select[name=search_mode]").change(function () {
        $("#search_mode").submit();

        });
    });
</script>
{% endblock %}

templates/sales/salesinfo_detail.html
{% extends 'base.html' %} <!-- extends는 상속이라는 뜻 -->
{% load humanize %}
{% block content %}
<hr align="center" width="30%">
<h2 align="center" style="margin-top:20px;">{{ salesinfo.scode }}</h2>
<!-- 제품 수정 버튼 시작 -->

<div align="center">
    <a href="{% url 'sales:salesinfo_modify' salesinfo.id %}" class="btn btn-sm btn-outline-secondary">판매 수정</a>
    <a href="#" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'sales:salesinfo_delete' salesinfo.id %}">판매 삭제</a>
</div>

<!-- 제품 수정 버튼 끝 -->
<hr align="center" width="30%"> <!-- 수평선 -->

<div style="width:100%; height:150px; padding:50px;">
    <table class="table">

        <tr class="thead-light">
            <th>키오스크코드</th>

            <th>세부기능</th>
            <th>판매일자</th>
            <th>판매수량</th>
            <th>판매금액</th>
            <th>구매처 분류</th>
            <th>상세주소</th>
        </tr>
        <tr>
            <td>
                {{ salesinfo.scode }}
            </td>

            <td>
                {{ product.detailfunc|join:", " }}

            </td>
            <td>
                {{ salesinfo.sale_date|date:'m월 d일 H:i' }}
            </td>
            <td>
                {{ salesinfo.qty }}
            </td>
            <td>
                {{ salesinfo.amt|intcomma }}
            </td>
            <td>
                {{ salesinfo.main_inst }}
            </td>
            <td>
                {{ salesinfo.detail_inst }}
            </td>
        </tr>
    </table>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}