common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
] # django.contrib.auth 앱의 LoginView 클래스 활용
# LoginView는 자동으로 registration 템플릿 디렉터리에서 login.html 찾아서 디렉터리 바꾸려면 template_name='' 하기

config/urls.py
from django.contrib import admin
from django.urls import path, include
from sales import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls')), # 원래는 'sales/' 였음. map 땜시 잠시 뺌
    path('common/', include('common.urls')),
    path('', views.map, name='map'), # / 페이지에 해당하는 urlpatterns
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.map, name='map'),
    path('<int:product_id>/', views.detail, name='detail'),
    path('product/create/', views.product_create, name='product_create'),
    path('product/modify/<int:product_id>/', views.product_modify, name='product_modify'),
    path('product/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product/product_list/', views.index, name='index'),
    path('salesinfo/', views.salesinfo_index, name='salesinfo_index'),
    path('salesinfo/<int:salesinfo_id>/', views.salesinfo_detail, name='salesinfo_detail'),
    path('salesinfo/crete/', views.salesinfo_create, name='salesinfo_create'),
    path('salesinfo/modify/<int:salesinfo_id>/', views.salesinfo_modify, name='salesinfo_modify'),
    path('salesinfo/delete/<int:salesinfo_id>/', views.salesinfo_delete, name='salesinfo_delete'),
]

templates/base.html
<!-- 템플릿 파일의 기본 틀 -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!--required meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, Sales!</title>
</head>
<body>
<!-- 내비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 끝 -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 end -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 입력값 누락이거나 형식에 맞지 않음 -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 입력값과 관계없이 발생한 오류 -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 내비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" xmlns="http://www.w3.org/1999/html"
     xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <a class="navbar-brand" href="{% url 'sales:map' %}">Kiosk Management System</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">  <!-- 양쪽 정렬, id는 햄버거 버튼과 연동되어 있으니 꼭 삽입 -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sales:index' %}">키오스크 조회</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sales:salesinfo_index' %}">판매 조회</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">커뮤니티</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item align-self-center">
                <!-- 로그인하면 내비게이션바에 로그아웃으로 뜨게 하기 -->
                {% if user.is_authenticated %}
                {{ user.username }}님, 안녕하세요! <!-- 로그인한 사용자명 -->
                {% endif %}
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">
                    <button type="button" class="btn btn-warning">logout</button>
                </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">
                    <button type="button" class="btn btn-info btn-sm">login</button>
                </a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>